abstract class PendingListStudentStatus{}
class PendingListStudentInitializeState extends PendingListStudentStatus{}
class PendingListStudentLoadingState extends PendingListStudentStatus{}
class PendingListStudentSuccessState extends PendingListStudentStatus{

}
class PendingListStudentErrorState extends PendingListStudentStatus{}